# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.0
maven_group=io.github.gcjojo
archives_name=questslib
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.11
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1
neoforge_version=21.1.252
liblib_version=0.2.0-dev2+1.21.1